# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "TalApi"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

#logger: log4perl
log: core
#engines:
#   logger:
#     log4perl:
#        config_file: log4perl.conf

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      ENCODING: utf8
      start_tag: '<%'
      end_tag:   '%>'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1

# plugins:
#   Auth::Extensible:
#     realms:
#       config:
#         provider: Config
#         users:
#           - user: tal
#             pass: test
#             roles:
#               - server
#               - third_party
basic_auth_user: tal
basic_auth_pass: test

plugins:
  OpenAPI:
    config: "config/talisman.json"
    processedby: "process_query"
    SQLLibrary:
      config:
        libraries:
           mysql: "sql/mysql.sql"
           beacon: "sql/bespoke.sql"
        mapping: "sql/mapping.sql"
        datasource: "sql/source.yml"

queries:
    GetTimesheetHistory:
        type: "select"
        table:
            timepool: |
                tp_timesheet_no
                tp_extranet_status
                tp_week_date, tp_week_no
                tp_json_entry
                tp_hours_tot
                tp_extranet_queried
                tp_extranet_query_type
                tp_extranet_query_reason
                tp_not_working
                tp_comment
            bookings: |
                oa_booking_no
                oa_assignment
            slclient: |
                cu_name
        where:
             bookings:
                oa_cust_code: slclient.cu_cust_code
                oa_cand_no: "params.candId"
             timepool:
                required:
                    tp_booking_no: bookings.oa_booking_no
                    tp_extranet_status:
                        in: |
                            Paid
                            Submitted
                            Approved
                            Entered
                optional:
                    tp_booking_no: "params.bookingNo"
    ListCandidates:
        type: "select"
        table:
            cands: "*"
    ListCustomers:
        type: "select"
        table:
            slcust: |
                cu_cust_code
                cu_name
    GetCustomer:
        type: "select"
        table:
            slcust: "*"
    GetOpenJobs:
        type: "select"
        table:
            job: "*"
        where:
            job:
                jb_job_status: Open
    GetJobDetails:
        type: "select"
        table:
            job: "*"
        where:
            jb_job_no: "params.jobNo"
    GetRateCodes:
        type: "select"
        table:
            ratecode: "*"
    GetBookingRateCodes:
        type: "select"
        table:
            bookings: |
                oa_booking_no
                oa_contractcust
                oa_payrate_no__1
                oa_payrate_no__2
                oa_payrate_no__3
                oa_payrate_no__4
                oa_payrate_no__5
                oa_payrate_no__6
                oa_payrate_no__7
                oa_payrate_no__8
        where:
            oa_cand_no: "params.candNo"
    GetBookingDetails:
        type: "select"
        table:
            bookings: "*"
        where:
            bookings:
                oa_booking_no: "params.bookingNo"
    GetBookings:
        type: "select"
        table:
            bookings: "*"
        where:
            bookings:
                oa_cand_no: "params.candId"
    GetBookingTimesheets:
        type: "select"
        table:
            timepool: "*"
        where:
            timepool:
                tp_booking_no: "params.bookingNo"
    GetTimesheetById:
        type: "select"
        table:
            timepool: "*"
            bookings: oa_assignment
            slclient: cu_name
            cands: "*"
        where:
            timepool:
                tp_timesheet_no: "params.timesheetNo"
            bookings:
                oa_booking_no: "timepool.tp_booking_no"
            slclient:
                cu_cuat_code: bookings.oa_cust_code
            cands:
                cand_cand_no: bookings.oa_cand_no
    GetTimesheet:        
        type: "select"
        table:
            timepool: "*"
            bookings: |
                oa_rate_hours__1
                oa_rate_hours__2
                oa_rate_hours__3
                oa_rate_hours__4
                oa_rate_hours__5
                oa_rate_hours__6
                oa_rate_hours__7
                oa_rate_hours__8
        where:
            timepool:
                tp_booking_no: "params.bookingNo"
                tp_week_date: "params.weekEndDate"
            bookings:
                oa_booking_no: "params.bookingNo"
    GetBlankTimesheets:
        type: "select"
        table:
            timepool: |
                tp_timesheet_no
                tp_week_date
        where:
            timepool:
                tp_booking_no: bookings.oa_booking_no
            bookings:
                oa_cand_no: params.candId
                oa_booking_no: params.bookingNo
    GetTimesheetHistory:
        type: "select"
        table:
            timepool: |
                tp_timesheet_no
                tp_extranet_status
                tp_week_date
                tp_week_no
                tp_json_entry
                tp_hours_tot
                tp_extranet_queried
                tp_extranet_query_type
                tp_extranet_query_reason
                tp_not_working
                tp_comment
            bookings: |
                oa_booking_no
                oa_assignment
            slclient: cu_name
        where:
            timepool:
                tp_booking_no: bookings.oa_booking_no
            bookings:
                oa_cand_no: "params.bookingNo"
            slclient:
                cu_cust_code: oa_cust_code
    UpdateTimesheet:
        type: "update"
        table: timepool
        where:
            timepool:
                tp_timesheet_no: params.timesheetNo
    InsertTimesheet:
        type: "insert"
        table: timepool
