# configuration file for staging environment

# only log warning and error messsages
#log: "warning"
log: "core"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

show_errors: 1

# disable server tokens in production environments
no_server_tokens: 1

startup_info: 0

dbname: dev
