$default_responses = { 200 => { description => 'success' },
                       default => { description => 'unexpected error' },
                       };
$api = {
    paths => {
        '/' => {
            get => {
                summary => 'Get Api Version Info',
                operationId => 'GetApiVersionInfo',
                responses => {
                    info => {
                        version => 'string',
                        contact => [ { name => 'string' } ],
                        title => 'string',
                        description => 'string',
                    },
                },
            },
        },
        '/openJobs' => {
            get => {
                summary => 'Get List of Open Jobs',
                operationId => 'GetOpenJobs',
                responses => {
                    openjobs => [ 'job.jb_job_no' ],
                },
            },
        },
        '/ratecodes' => {
            get => {
                summary => 'List Talisman rate codes',
                operationId => 'GetRateCodes',
                responses => {
                    ratecodes => [
                        'ratecode.rc_payrate_no',
                        'ratecode.rc_pay_type',
                        'ratecode.rc_pay_tax',
                        'ratecode.rc_pay_vatonly',
                        'ratecode.rc_pay_factor',
                        'ratecode.rc_pay_desc',
                        'ratecode.rc_rate_desc',
                        'ratecode.rc_pay_spec',
                        'ratecode.rc_pay_rate',
                        'ratecode.rc_inv_vattype',
                        'ratecode.rc_inv_vatonly',
                        'ratecode.rc_inv_factor',
                        'ratecode.rc_inv_rate',
                        'ratecode.rc_factor_code',
                        'ratecode.rc_hrs_day'
                    ],
                },
            }
        },
        '/bookings' => {
            get => {
                summary => 'Returns bookings',
                operationId => 'GetBookings',
                responses => {
                    bookings => [ 'bookings.oa_booking_no' ],
                },
            },
        },
        '/booking/{bookingNo}/{workweekEndDate}' => {
            'get' => {
                summary => 'Returns rate codes, limits, pay rates for a booking, any existing timesheet detail record for that booking and workwkend',
                operationId => 'GetBookingTimesheets',
                parameters => { bookingNo       => { sql => 'bookings.oa_booking_no', desc => "Booking Number" },
                                workweekEndDate => { sql => 'timesheet.th_paywkend', desc => "Date of week end" },
                                },
                responses => {
                    bookingtimesheets => [ 'timesheet.th_timesheet_no' ],
                },
            },
        },
        '/candidate' => {
            post => {
                summary => 'Adds a new candidate',
                operationId => 'AddCandidate',
                parameters => {

cand_ack_ts => { sql => "cands.cand_ack_ts", desc => "cand_ack_ts" },
cand_add5 => { sql => "cands.cand_add5", desc => "cand_add5" },
cand_add_remit => { sql => "cands.cand_add_remit", desc => "cand_add_remit" },
cand_add_ts => { sql => "cands.cand_add_ts", desc => "cand_add_ts" },
cand_address__1 => { sql => "cands.cand_address__1", desc => "cand_address__1" },
cand_address__2 => { sql => "cands.cand_address__2", desc => "cand_address__2" },
cand_address__3 => { sql => "cands.cand_address__3", desc => "cand_address__3" },
cand_address__4 => { sql => "cands.cand_address__4", desc => "cand_address__4" },
cand_advert => { sql => "cands.cand_advert", desc => "cand_advert" },
cand_age => { sql => "cands.cand_age", desc => "cand_age" },
cand_alt_address__1 => { sql => "cands.cand_alt_address__1", desc => "cand_alt_address__1" },
cand_alt_address__2 => { sql => "cands.cand_alt_address__2", desc => "cand_alt_address__2" },
cand_alt_address__3 => { sql => "cands.cand_alt_address__3", desc => "cand_alt_address__3" },
cand_alt_address__4 => { sql => "cands.cand_alt_address__4", desc => "cand_alt_address__4" },
cand_alt_address__5 => { sql => "cands.cand_alt_address__5", desc => "cand_alt_address__5" },
cand_amend_by => { sql => "cands.cand_amend_by", desc => "cand_amend_by" },
cand_amend_on => { sql => "cands.cand_amend_on", desc => "cand_amend_on" },
cand_area__1 => { sql => "cands.cand_area__1", desc => "cand_area__1" },
cand_area__2 => { sql => "cands.cand_area__2", desc => "cand_area__2" },
cand_area__3 => { sql => "cands.cand_area__3", desc => "cand_area__3" },
cand_area__4 => { sql => "cands.cand_area__4", desc => "cand_area__4" },
cand_area__5 => { sql => "cands.cand_area__5", desc => "cand_area__5" },
cand_area__6 => { sql => "cands.cand_area__6", desc => "cand_area__6" },
cand_area__7 => { sql => "cands.cand_area__7", desc => "cand_area__7" },
cand_area__8 => { sql => "cands.cand_area__8", desc => "cand_area__8" },
cand_area__9 => { sql => "cands.cand_area__9", desc => "cand_area__9" },
cand_avail => { sql => "cands.cand_avail", desc => "cand_avail" },
cand_avail_1 => { sql => "cands.cand_avail_1", desc => "cand_avail_1" },
cand_avail_dur => { sql => "cands.cand_avail_dur", desc => "cand_avail_dur" },
cand_avail_flag => { sql => "cands.cand_avail_flag", desc => "cand_avail_flag" },
cand_avail_grid_dt => { sql => "cands.cand_avail_grid_dt", desc => "cand_avail_grid_dt" },
cand_bon_hrs => { sql => "cands.cand_bon_hrs", desc => "cand_bon_hrs" },
cand_bon_level => { sql => "cands.cand_bon_level", desc => "cand_bon_level" },
cand_borrowed => { sql => "cands.cand_borrowed", desc => "cand_borrowed" },
cand_branch => { sql => "cands.cand_branch", desc => "cand_branch" },
cand_branch_no => { sql => "cands.cand_branch_no", desc => "cand_branch_no" },
cand_cand_no => { sql => "cands.cand_cand_no", desc => "cand_cand_no" },
cand_code => { sql => "cands.cand_code", desc => "cand_code" },
cand_comment1 => { sql => "cands.cand_comment1", desc => "cand_comment1" },
cand_comp_name => { sql => "cands.cand_comp_name", desc => "cand_comp_name" },
cand_consultant => { sql => "cands.cand_consultant", desc => "cand_consultant" },
cand_country => { sql => "cands.cand_country", desc => "cand_country" },
cand_crb_disc_no => { sql => "cands.cand_crb_disc_no", desc => "cand_crb_disc_no" },
cand_curr_agent => { sql => "cands.cand_curr_agent", desc => "cand_curr_agent" },
cand_curr_co => { sql => "cands.cand_curr_co", desc => "cand_curr_co" },
cand_curr_rate => { sql => "cands.cand_curr_rate", desc => "cand_curr_rate" },
cand_curr_rate_halfday => { sql => "cands.cand_curr_rate_halfday", desc => "cand_curr_rate_halfday" },
cand_currpos => { sql => "cands.cand_currpos", desc => "cand_currpos" },
cand_currsal => { sql => "cands.cand_currsal", desc => "cand_currsal" },
cand_cv_date => { sql => "cands.cand_cv_date", desc => "cand_cv_date" },
cand_d_amend_by => { sql => "cands.cand_d_amend_by", desc => "cand_d_amend_by" },
cand_d_amend_on => { sql => "cands.cand_d_amend_on", desc => "cand_d_amend_on" },
cand_date_trans => { sql => "cands.cand_date_trans", desc => "cand_date_trans" },
cand_day_rate => { sql => "cands.cand_day_rate", desc => "cand_day_rate" },
cand_degree_1 => { sql => "cands.cand_degree_1", desc => "cand_degree_1" },
cand_dob => { sql => "cands.cand_dob", desc => "cand_dob" },
cand_driving_licence => { sql => "cands.cand_driving_licence", desc => "cand_driving_licence" },
cand_email => { sql => "cands.cand_email", desc => "cand_email" },
cand_email2 => { sql => "cands.cand_email2", desc => "cand_email2" },
cand_eo_disability => { sql => "cands.cand_eo_disability", desc => "cand_eo_disability" },
cand_eo_disability_txt => { sql => "cands.cand_eo_disability_txt", desc => "cand_eo_disability_txt" },
cand_eo_ethnicity => { sql => "cands.cand_eo_ethnicity", desc => "cand_eo_ethnicity" },
cand_eo_exoffender => { sql => "cands.cand_eo_exoffender", desc => "cand_eo_exoffender" },
cand_eo_exoffender_txt => { sql => "cands.cand_eo_exoffender_txt", desc => "cand_eo_exoffender_txt" },
cand_eo_religion => { sql => "cands.cand_eo_religion", desc => "cand_eo_religion" },
cand_eo_sexorientation => { sql => "cands.cand_eo_sexorientation", desc => "cand_eo_sexorientation" },
cand_external_id => { sql => "cands.cand_external_id", desc => "cand_external_id" },
cand_forename => { sql => "cands.cand_forename", desc => "cand_forename" },
cand_group => { sql => "cands.cand_group", desc => "cand_group" },
cand_h_amend_on => { sql => "cands.cand_h_amend_on", desc => "cand_h_amend_on" },
cand_hours_opt => { sql => "cands.cand_hours_opt", desc => "cand_hours_opt" },
cand_hrs_wkd => { sql => "cands.cand_hrs_wkd", desc => "cand_hrs_wkd" },
cand_initials => { sql => "cands.cand_initials", desc => "cand_initials" },
cand_intby => { sql => "cands.cand_intby", desc => "cand_intby" },
cand_iv_stat => { sql => "cands.cand_iv_stat", desc => "cand_iv_stat" },
cand_job_discipline => { sql => "cands.cand_job_discipline", desc => "cand_job_discipline" },
cand_job_level => { sql => "cands.cand_job_level", desc => "cand_job_level" },
cand_knownas => { sql => "cands.cand_knownas", desc => "cand_knownas" },
cand_last_con => { sql => "cands.cand_last_con", desc => "cand_last_con" },
cand_lastcon_by => { sql => "cands.cand_lastcon_by", desc => "cand_lastcon_by" },
cand_lett_opts1 => { sql => "cands.cand_lett_opts1", desc => "cand_lett_opts1" },
cand_ltr_brh => { sql => "cands.cand_ltr_brh", desc => "cand_ltr_brh" },
cand_ltr_conslt => { sql => "cands.cand_ltr_conslt", desc => "cand_ltr_conslt" },
cand_mailallow_email => { sql => "cands.cand_mailallow_email", desc => "cand_mailallow_email" },
cand_mailallow_fax => { sql => "cands.cand_mailallow_fax", desc => "cand_mailallow_fax" },
cand_mailallow_sms => { sql => "cands.cand_mailallow_sms", desc => "cand_mailallow_sms" },
cand_mailpref => { sql => "cands.cand_mailpref", desc => "cand_mailpref" },
cand_mailpref_default => { sql => "cands.cand_mailpref_default", desc => "cand_mailpref_default" },
cand_mailpref_email => { sql => "cands.cand_mailpref_email", desc => "cand_mailpref_email" },
cand_mailpref_fax => { sql => "cands.cand_mailpref_fax", desc => "cand_mailpref_fax" },
cand_mailpref_sms => { sql => "cands.cand_mailpref_sms", desc => "cand_mailpref_sms" },
cand_mailshot => { sql => "cands.cand_mailshot", desc => "cand_mailshot" },
cand_marital => { sql => "cands.cand_marital", desc => "cand_marital" },
cand_mobile => { sql => "cands.cand_mobile", desc => "cand_mobile" },
cand_mobile2 => { sql => "cands.cand_mobile2", desc => "cand_mobile2" },
cand_mother_maiden_name => { sql => "cands.cand_mother_maiden_name", desc => "cand_mother_maiden_name" },
cand_national => { sql => "cands.cand_national", desc => "cand_national" },
cand_new_area => { sql => "cands.cand_new_area", desc => "cand_new_area" },
cand_next_of_kin => { sql => "cands.cand_next_of_kin", desc => "cand_next_of_kin" },
cand_no_rev => { sql => "cands.cand_no_rev", desc => "cand_no_rev" },
cand_notice => { sql => "cands.cand_notice", desc => "cand_notice" },
cand_oa_last => { sql => "cands.cand_oa_last", desc => "cand_oa_last" },
cand_os_police_clear_no => { sql => "cands.cand_os_police_clear_no", desc => "cand_os_police_clear_no" },
cand_otherco => { sql => "cands.cand_otherco", desc => "cand_otherco" },
cand_othercomps__1 => { sql => "cands.cand_othercomps__1", desc => "cand_othercomps__1" },
cand_othercomps__2 => { sql => "cands.cand_othercomps__2", desc => "cand_othercomps__2" },
cand_othercomps__3 => { sql => "cands.cand_othercomps__3", desc => "cand_othercomps__3" },
cand_othercomps__4 => { sql => "cands.cand_othercomps__4", desc => "cand_othercomps__4" },
cand_othercomps__5 => { sql => "cands.cand_othercomps__5", desc => "cand_othercomps__5" },
cand_owncar => { sql => "cands.cand_owncar", desc => "cand_owncar" },
cand_owncv => { sql => "cands.cand_owncv", desc => "cand_owncv" },
cand_passport_expiry_date => { sql => "cands.cand_passport_expiry_date", desc => "cand_passport_expiry_date" },
cand_passport_issue_date => { sql => "cands.cand_passport_issue_date", desc => "cand_passport_issue_date" },
cand_passport_issued_by => { sql => "cands.cand_passport_issued_by", desc => "cand_passport_issued_by" },
cand_passport_no => { sql => "cands.cand_passport_no", desc => "cand_passport_no" },
cand_pay_comm => { sql => "cands.cand_pay_comm", desc => "cand_pay_comm" },
cand_pay_end => { sql => "cands.cand_pay_end", desc => "cand_pay_end" },
cand_pay_reason => { sql => "cands.cand_pay_reason", desc => "cand_pay_reason" },
cand_pay_start => { sql => "cands.cand_pay_start", desc => "cand_pay_start" },
cand_pay_type => { sql => "cands.cand_pay_type", desc => "cand_pay_type" },
cand_pay_type1 => { sql => "cands.cand_pay_type1", desc => "cand_pay_type1" },
cand_payroll => { sql => "cands.cand_payroll", desc => "cand_payroll" },
cand_phone => { sql => "cands.cand_phone", desc => "cand_phone" },
cand_pl_supp => { sql => "cands.cand_pl_supp", desc => "cand_pl_supp" },
cand_place_of_birth => { sql => "cands.cand_place_of_birth", desc => "cand_place_of_birth" },
cand_postcode => { sql => "cands.cand_postcode", desc => "cand_postcode" },
cand_postcode2 => { sql => "cands.cand_postcode2", desc => "cand_postcode2" },
cand_postcode_area => { sql => "cands.cand_postcode_area", desc => "cand_postcode_area" },
cand_prof_reg_no => { sql => "cands.cand_prof_reg_no", desc => "cand_prof_reg_no" },
cand_ref1_recv_dt => { sql => "cands.cand_ref1_recv_dt", desc => "cand_ref1_recv_dt" },
cand_ref1_send_dt => { sql => "cands.cand_ref1_send_dt", desc => "cand_ref1_send_dt" },
cand_ref2_recv_dt => { sql => "cands.cand_ref2_recv_dt", desc => "cand_ref2_recv_dt" },
cand_ref2_send_dt => { sql => "cands.cand_ref2_send_dt", desc => "cand_ref2_send_dt" },
cand_refer_to => { sql => "cands.cand_refer_to", desc => "cand_refer_to" },
cand_reg_date => { sql => "cands.cand_reg_date", desc => "cand_reg_date" },
cand_retained => { sql => "cands.cand_retained", desc => "cand_retained" },
cand_salu => { sql => "cands.cand_salu", desc => "cand_salu" },
cand_scan => { sql => "cands.cand_scan", desc => "cand_scan" },
cand_security_no => { sql => "cands.cand_security_no", desc => "cand_security_no" },
cand_sex => { sql => "cands.cand_sex", desc => "cand_sex" },
cand_skill_code__1 => { sql => "cands.cand_skill_code__1", desc => "cand_skill_code__1" },
cand_skill_code__10 => { sql => "cands.cand_skill_code__10", desc => "cand_skill_code__10" },
cand_skill_code__11 => { sql => "cands.cand_skill_code__11", desc => "cand_skill_code__11" },
cand_skill_code__12 => { sql => "cands.cand_skill_code__12", desc => "cand_skill_code__12" },
cand_skill_code__13 => { sql => "cands.cand_skill_code__13", desc => "cand_skill_code__13" },
cand_skill_code__14 => { sql => "cands.cand_skill_code__14", desc => "cand_skill_code__14" },
cand_skill_code__15 => { sql => "cands.cand_skill_code__15", desc => "cand_skill_code__15" },
cand_skill_code__16 => { sql => "cands.cand_skill_code__16", desc => "cand_skill_code__16" },
cand_skill_code__17 => { sql => "cands.cand_skill_code__17", desc => "cand_skill_code__17" },
cand_skill_code__18 => { sql => "cands.cand_skill_code__18", desc => "cand_skill_code__18" },
cand_skill_code__19 => { sql => "cands.cand_skill_code__19", desc => "cand_skill_code__19" },
cand_skill_code__2 => { sql => "cands.cand_skill_code__2", desc => "cand_skill_code__2" },
cand_skill_code__20 => { sql => "cands.cand_skill_code__20", desc => "cand_skill_code__20" },
cand_skill_code__21 => { sql => "cands.cand_skill_code__21", desc => "cand_skill_code__21" },
cand_skill_code__22 => { sql => "cands.cand_skill_code__22", desc => "cand_skill_code__22" },
cand_skill_code__23 => { sql => "cands.cand_skill_code__23", desc => "cand_skill_code__23" },
cand_skill_code__24 => { sql => "cands.cand_skill_code__24", desc => "cand_skill_code__24" },
cand_skill_code__25 => { sql => "cands.cand_skill_code__25", desc => "cand_skill_code__25" },
cand_skill_code__26 => { sql => "cands.cand_skill_code__26", desc => "cand_skill_code__26" },
cand_skill_code__27 => { sql => "cands.cand_skill_code__27", desc => "cand_skill_code__27" },
cand_skill_code__28 => { sql => "cands.cand_skill_code__28", desc => "cand_skill_code__28" },
cand_skill_code__29 => { sql => "cands.cand_skill_code__29", desc => "cand_skill_code__29" },
cand_skill_code__3 => { sql => "cands.cand_skill_code__3", desc => "cand_skill_code__3" },
cand_skill_code__30 => { sql => "cands.cand_skill_code__30", desc => "cand_skill_code__30" },
cand_skill_code__31 => { sql => "cands.cand_skill_code__31", desc => "cand_skill_code__31" },
cand_skill_code__32 => { sql => "cands.cand_skill_code__32", desc => "cand_skill_code__32" },
cand_skill_code__33 => { sql => "cands.cand_skill_code__33", desc => "cand_skill_code__33" },
cand_skill_code__34 => { sql => "cands.cand_skill_code__34", desc => "cand_skill_code__34" },
cand_skill_code__35 => { sql => "cands.cand_skill_code__35", desc => "cand_skill_code__35" },
cand_skill_code__36 => { sql => "cands.cand_skill_code__36", desc => "cand_skill_code__36" },
cand_skill_code__37 => { sql => "cands.cand_skill_code__37", desc => "cand_skill_code__37" },
cand_skill_code__38 => { sql => "cands.cand_skill_code__38", desc => "cand_skill_code__38" },
cand_skill_code__39 => { sql => "cands.cand_skill_code__39", desc => "cand_skill_code__39" },
cand_skill_code__4 => { sql => "cands.cand_skill_code__4", desc => "cand_skill_code__4" },
cand_skill_code__40 => { sql => "cands.cand_skill_code__40", desc => "cand_skill_code__40" },
cand_skill_code__41 => { sql => "cands.cand_skill_code__41", desc => "cand_skill_code__41" },
cand_skill_code__42 => { sql => "cands.cand_skill_code__42", desc => "cand_skill_code__42" },
cand_skill_code__43 => { sql => "cands.cand_skill_code__43", desc => "cand_skill_code__43" },
cand_skill_code__44 => { sql => "cands.cand_skill_code__44", desc => "cand_skill_code__44" },
cand_skill_code__45 => { sql => "cands.cand_skill_code__45", desc => "cand_skill_code__45" },
cand_skill_code__46 => { sql => "cands.cand_skill_code__46", desc => "cand_skill_code__46" },
cand_skill_code__47 => { sql => "cands.cand_skill_code__47", desc => "cand_skill_code__47" },
cand_skill_code__48 => { sql => "cands.cand_skill_code__48", desc => "cand_skill_code__48" },
cand_skill_code__49 => { sql => "cands.cand_skill_code__49", desc => "cand_skill_code__49" },
cand_skill_code__5 => { sql => "cands.cand_skill_code__5", desc => "cand_skill_code__5" },
cand_skill_code__50 => { sql => "cands.cand_skill_code__50", desc => "cand_skill_code__50" },
cand_skill_code__51 => { sql => "cands.cand_skill_code__51", desc => "cand_skill_code__51" },
cand_skill_code__52 => { sql => "cands.cand_skill_code__52", desc => "cand_skill_code__52" },
cand_skill_code__53 => { sql => "cands.cand_skill_code__53", desc => "cand_skill_code__53" },
cand_skill_code__54 => { sql => "cands.cand_skill_code__54", desc => "cand_skill_code__54" },
cand_skill_code__55 => { sql => "cands.cand_skill_code__55", desc => "cand_skill_code__55" },
cand_skill_code__56 => { sql => "cands.cand_skill_code__56", desc => "cand_skill_code__56" },
cand_skill_code__57 => { sql => "cands.cand_skill_code__57", desc => "cand_skill_code__57" },
cand_skill_code__58 => { sql => "cands.cand_skill_code__58", desc => "cand_skill_code__58" },
cand_skill_code__59 => { sql => "cands.cand_skill_code__59", desc => "cand_skill_code__59" },
cand_skill_code__6 => { sql => "cands.cand_skill_code__6", desc => "cand_skill_code__6" },
cand_skill_code__60 => { sql => "cands.cand_skill_code__60", desc => "cand_skill_code__60" },
cand_skill_code__7 => { sql => "cands.cand_skill_code__7", desc => "cand_skill_code__7" },
cand_skill_code__8 => { sql => "cands.cand_skill_code__8", desc => "cand_skill_code__8" },
cand_skill_code__9 => { sql => "cands.cand_skill_code__9", desc => "cand_skill_code__9" },
cand_skill_levl__1 => { sql => "cands.cand_skill_levl__1", desc => "cand_skill_levl__1" },
cand_skill_levl__10 => { sql => "cands.cand_skill_levl__10", desc => "cand_skill_levl__10" },
cand_skill_levl__11 => { sql => "cands.cand_skill_levl__11", desc => "cand_skill_levl__11" },
cand_skill_levl__12 => { sql => "cands.cand_skill_levl__12", desc => "cand_skill_levl__12" },
cand_skill_levl__13 => { sql => "cands.cand_skill_levl__13", desc => "cand_skill_levl__13" },
cand_skill_levl__14 => { sql => "cands.cand_skill_levl__14", desc => "cand_skill_levl__14" },
cand_skill_levl__15 => { sql => "cands.cand_skill_levl__15", desc => "cand_skill_levl__15" },
cand_skill_levl__16 => { sql => "cands.cand_skill_levl__16", desc => "cand_skill_levl__16" },
cand_skill_levl__17 => { sql => "cands.cand_skill_levl__17", desc => "cand_skill_levl__17" },
cand_skill_levl__18 => { sql => "cands.cand_skill_levl__18", desc => "cand_skill_levl__18" },
cand_skill_levl__19 => { sql => "cands.cand_skill_levl__19", desc => "cand_skill_levl__19" },
cand_skill_levl__2 => { sql => "cands.cand_skill_levl__2", desc => "cand_skill_levl__2" },
cand_skill_levl__20 => { sql => "cands.cand_skill_levl__20", desc => "cand_skill_levl__20" },
cand_skill_levl__21 => { sql => "cands.cand_skill_levl__21", desc => "cand_skill_levl__21" },
cand_skill_levl__22 => { sql => "cands.cand_skill_levl__22", desc => "cand_skill_levl__22" },
cand_skill_levl__23 => { sql => "cands.cand_skill_levl__23", desc => "cand_skill_levl__23" },
cand_skill_levl__24 => { sql => "cands.cand_skill_levl__24", desc => "cand_skill_levl__24" },
cand_skill_levl__25 => { sql => "cands.cand_skill_levl__25", desc => "cand_skill_levl__25" },
cand_skill_levl__26 => { sql => "cands.cand_skill_levl__26", desc => "cand_skill_levl__26" },
cand_skill_levl__27 => { sql => "cands.cand_skill_levl__27", desc => "cand_skill_levl__27" },
cand_skill_levl__28 => { sql => "cands.cand_skill_levl__28", desc => "cand_skill_levl__28" },
cand_skill_levl__29 => { sql => "cands.cand_skill_levl__29", desc => "cand_skill_levl__29" },
cand_skill_levl__3 => { sql => "cands.cand_skill_levl__3", desc => "cand_skill_levl__3" },
cand_skill_levl__30 => { sql => "cands.cand_skill_levl__30", desc => "cand_skill_levl__30" },
cand_skill_levl__31 => { sql => "cands.cand_skill_levl__31", desc => "cand_skill_levl__31" },
cand_skill_levl__32 => { sql => "cands.cand_skill_levl__32", desc => "cand_skill_levl__32" },
cand_skill_levl__33 => { sql => "cands.cand_skill_levl__33", desc => "cand_skill_levl__33" },
cand_skill_levl__34 => { sql => "cands.cand_skill_levl__34", desc => "cand_skill_levl__34" },
cand_skill_levl__35 => { sql => "cands.cand_skill_levl__35", desc => "cand_skill_levl__35" },
cand_skill_levl__36 => { sql => "cands.cand_skill_levl__36", desc => "cand_skill_levl__36" },
cand_skill_levl__37 => { sql => "cands.cand_skill_levl__37", desc => "cand_skill_levl__37" },
cand_skill_levl__38 => { sql => "cands.cand_skill_levl__38", desc => "cand_skill_levl__38" },
cand_skill_levl__39 => { sql => "cands.cand_skill_levl__39", desc => "cand_skill_levl__39" },
cand_skill_levl__4 => { sql => "cands.cand_skill_levl__4", desc => "cand_skill_levl__4" },
cand_skill_levl__40 => { sql => "cands.cand_skill_levl__40", desc => "cand_skill_levl__40" },
cand_skill_levl__41 => { sql => "cands.cand_skill_levl__41", desc => "cand_skill_levl__41" },
cand_skill_levl__42 => { sql => "cands.cand_skill_levl__42", desc => "cand_skill_levl__42" },
cand_skill_levl__43 => { sql => "cands.cand_skill_levl__43", desc => "cand_skill_levl__43" },
cand_skill_levl__44 => { sql => "cands.cand_skill_levl__44", desc => "cand_skill_levl__44" },
cand_skill_levl__45 => { sql => "cands.cand_skill_levl__45", desc => "cand_skill_levl__45" },
cand_skill_levl__46 => { sql => "cands.cand_skill_levl__46", desc => "cand_skill_levl__46" },
cand_skill_levl__47 => { sql => "cands.cand_skill_levl__47", desc => "cand_skill_levl__47" },
cand_skill_levl__48 => { sql => "cands.cand_skill_levl__48", desc => "cand_skill_levl__48" },
cand_skill_levl__49 => { sql => "cands.cand_skill_levl__49", desc => "cand_skill_levl__49" },
cand_skill_levl__5 => { sql => "cands.cand_skill_levl__5", desc => "cand_skill_levl__5" },
cand_skill_levl__50 => { sql => "cands.cand_skill_levl__50", desc => "cand_skill_levl__50" },
cand_skill_levl__51 => { sql => "cands.cand_skill_levl__51", desc => "cand_skill_levl__51" },
cand_skill_levl__52 => { sql => "cands.cand_skill_levl__52", desc => "cand_skill_levl__52" },
cand_skill_levl__53 => { sql => "cands.cand_skill_levl__53", desc => "cand_skill_levl__53" },
cand_skill_levl__54 => { sql => "cands.cand_skill_levl__54", desc => "cand_skill_levl__54" },
cand_skill_levl__55 => { sql => "cands.cand_skill_levl__55", desc => "cand_skill_levl__55" },
cand_skill_levl__56 => { sql => "cands.cand_skill_levl__56", desc => "cand_skill_levl__56" },
cand_skill_levl__57 => { sql => "cands.cand_skill_levl__57", desc => "cand_skill_levl__57" },
cand_skill_levl__58 => { sql => "cands.cand_skill_levl__58", desc => "cand_skill_levl__58" },
cand_skill_levl__59 => { sql => "cands.cand_skill_levl__59", desc => "cand_skill_levl__59" },
cand_skill_levl__6 => { sql => "cands.cand_skill_levl__6", desc => "cand_skill_levl__6" },
cand_skill_levl__60 => { sql => "cands.cand_skill_levl__60", desc => "cand_skill_levl__60" },
cand_skill_levl__7 => { sql => "cands.cand_skill_levl__7", desc => "cand_skill_levl__7" },
cand_skill_levl__8 => { sql => "cands.cand_skill_levl__8", desc => "cand_skill_levl__8" },
cand_skill_levl__9 => { sql => "cands.cand_skill_levl__9", desc => "cand_skill_levl__9" },
cand_social_media_id__1 => { sql => "cands.cand_social_media_id__1", desc => "cand_social_media_id__1" },
cand_social_media_id__2 => { sql => "cands.cand_social_media_id__2", desc => "cand_social_media_id__2" },
cand_social_media_id__3 => { sql => "cands.cand_social_media_id__3", desc => "cand_social_media_id__3" },
cand_social_media_id__4 => { sql => "cands.cand_social_media_id__4", desc => "cand_social_media_id__4" },
cand_social_media_id__5 => { sql => "cands.cand_social_media_id__5", desc => "cand_social_media_id__5" },
cand_social_media_type__1 => { sql => "cands.cand_social_media_type__1", desc => "cand_social_media_type__1" },
cand_social_media_type__2 => { sql => "cands.cand_social_media_type__2", desc => "cand_social_media_type__2" },
cand_social_media_type__3 => { sql => "cands.cand_social_media_type__3", desc => "cand_social_media_type__3" },
cand_social_media_type__4 => { sql => "cands.cand_social_media_type__4", desc => "cand_social_media_type__4" },
cand_social_media_type__5 => { sql => "cands.cand_social_media_type__5", desc => "cand_social_media_type__5" },
cand_soft_1 => { sql => "cands.cand_soft_1", desc => "cand_soft_1" },
cand_soft_10 => { sql => "cands.cand_soft_10", desc => "cand_soft_10" },
cand_soft_11 => { sql => "cands.cand_soft_11", desc => "cand_soft_11" },
cand_soft_12 => { sql => "cands.cand_soft_12", desc => "cand_soft_12" },
cand_soft_13 => { sql => "cands.cand_soft_13", desc => "cand_soft_13" },
cand_soft_14 => { sql => "cands.cand_soft_14", desc => "cand_soft_14" },
cand_soft_15 => { sql => "cands.cand_soft_15", desc => "cand_soft_15" },
cand_soft_16 => { sql => "cands.cand_soft_16", desc => "cand_soft_16" },
cand_soft_17 => { sql => "cands.cand_soft_17", desc => "cand_soft_17" },
cand_soft_18 => { sql => "cands.cand_soft_18", desc => "cand_soft_18" },
cand_soft_19 => { sql => "cands.cand_soft_19", desc => "cand_soft_19" },
cand_soft_2 => { sql => "cands.cand_soft_2", desc => "cand_soft_2" },
cand_soft_20 => { sql => "cands.cand_soft_20", desc => "cand_soft_20" },
cand_soft_21 => { sql => "cands.cand_soft_21", desc => "cand_soft_21" },
cand_soft_22 => { sql => "cands.cand_soft_22", desc => "cand_soft_22" },
cand_soft_23 => { sql => "cands.cand_soft_23", desc => "cand_soft_23" },
cand_soft_24 => { sql => "cands.cand_soft_24", desc => "cand_soft_24" },
cand_soft_25 => { sql => "cands.cand_soft_25", desc => "cand_soft_25" },
cand_soft_26 => { sql => "cands.cand_soft_26", desc => "cand_soft_26" },
cand_soft_27 => { sql => "cands.cand_soft_27", desc => "cand_soft_27" },
cand_soft_28 => { sql => "cands.cand_soft_28", desc => "cand_soft_28" },
cand_soft_29 => { sql => "cands.cand_soft_29", desc => "cand_soft_29" },
cand_soft_3 => { sql => "cands.cand_soft_3", desc => "cand_soft_3" },
cand_soft_30 => { sql => "cands.cand_soft_30", desc => "cand_soft_30" },
cand_soft_31 => { sql => "cands.cand_soft_31", desc => "cand_soft_31" },
cand_soft_32 => { sql => "cands.cand_soft_32", desc => "cand_soft_32" },
cand_soft_33 => { sql => "cands.cand_soft_33", desc => "cand_soft_33" },
cand_soft_34 => { sql => "cands.cand_soft_34", desc => "cand_soft_34" },
cand_soft_35 => { sql => "cands.cand_soft_35", desc => "cand_soft_35" },
cand_soft_36 => { sql => "cands.cand_soft_36", desc => "cand_soft_36" },
cand_soft_37 => { sql => "cands.cand_soft_37", desc => "cand_soft_37" },
cand_soft_38 => { sql => "cands.cand_soft_38", desc => "cand_soft_38" },
cand_soft_39 => { sql => "cands.cand_soft_39", desc => "cand_soft_39" },
cand_soft_4 => { sql => "cands.cand_soft_4", desc => "cand_soft_4" },
cand_soft_40 => { sql => "cands.cand_soft_40", desc => "cand_soft_40" },
cand_soft_5 => { sql => "cands.cand_soft_5", desc => "cand_soft_5" },
cand_soft_6 => { sql => "cands.cand_soft_6", desc => "cand_soft_6" },
cand_soft_7 => { sql => "cands.cand_soft_7", desc => "cand_soft_7" },
cand_soft_8 => { sql => "cands.cand_soft_8", desc => "cand_soft_8" },
cand_soft_9 => { sql => "cands.cand_soft_9", desc => "cand_soft_9" },
cand_soft_desc_1 => { sql => "cands.cand_soft_desc_1", desc => "cand_soft_desc_1" },
cand_soft_desc_10 => { sql => "cands.cand_soft_desc_10", desc => "cand_soft_desc_10" },
cand_soft_desc_11 => { sql => "cands.cand_soft_desc_11", desc => "cand_soft_desc_11" },
cand_soft_desc_12 => { sql => "cands.cand_soft_desc_12", desc => "cand_soft_desc_12" },
cand_soft_desc_13 => { sql => "cands.cand_soft_desc_13", desc => "cand_soft_desc_13" },
cand_soft_desc_14 => { sql => "cands.cand_soft_desc_14", desc => "cand_soft_desc_14" },
cand_soft_desc_15 => { sql => "cands.cand_soft_desc_15", desc => "cand_soft_desc_15" },
cand_soft_desc_16 => { sql => "cands.cand_soft_desc_16", desc => "cand_soft_desc_16" },
cand_soft_desc_17 => { sql => "cands.cand_soft_desc_17", desc => "cand_soft_desc_17" },
cand_soft_desc_18 => { sql => "cands.cand_soft_desc_18", desc => "cand_soft_desc_18" },
cand_soft_desc_19 => { sql => "cands.cand_soft_desc_19", desc => "cand_soft_desc_19" },
cand_soft_desc_2 => { sql => "cands.cand_soft_desc_2", desc => "cand_soft_desc_2" },
cand_soft_desc_20 => { sql => "cands.cand_soft_desc_20", desc => "cand_soft_desc_20" },
cand_soft_desc_21 => { sql => "cands.cand_soft_desc_21", desc => "cand_soft_desc_21" },
cand_soft_desc_22 => { sql => "cands.cand_soft_desc_22", desc => "cand_soft_desc_22" },
cand_soft_desc_23 => { sql => "cands.cand_soft_desc_23", desc => "cand_soft_desc_23" },
cand_soft_desc_24 => { sql => "cands.cand_soft_desc_24", desc => "cand_soft_desc_24" },
cand_soft_desc_25 => { sql => "cands.cand_soft_desc_25", desc => "cand_soft_desc_25" },
cand_soft_desc_26 => { sql => "cands.cand_soft_desc_26", desc => "cand_soft_desc_26" },
cand_soft_desc_27 => { sql => "cands.cand_soft_desc_27", desc => "cand_soft_desc_27" },
cand_soft_desc_28 => { sql => "cands.cand_soft_desc_28", desc => "cand_soft_desc_28" },
cand_soft_desc_29 => { sql => "cands.cand_soft_desc_29", desc => "cand_soft_desc_29" },
cand_soft_desc_3 => { sql => "cands.cand_soft_desc_3", desc => "cand_soft_desc_3" },
cand_soft_desc_30 => { sql => "cands.cand_soft_desc_30", desc => "cand_soft_desc_30" },
cand_soft_desc_31 => { sql => "cands.cand_soft_desc_31", desc => "cand_soft_desc_31" },
cand_soft_desc_32 => { sql => "cands.cand_soft_desc_32", desc => "cand_soft_desc_32" },
cand_soft_desc_33 => { sql => "cands.cand_soft_desc_33", desc => "cand_soft_desc_33" },
cand_soft_desc_34 => { sql => "cands.cand_soft_desc_34", desc => "cand_soft_desc_34" },
cand_soft_desc_35 => { sql => "cands.cand_soft_desc_35", desc => "cand_soft_desc_35" },
cand_soft_desc_36 => { sql => "cands.cand_soft_desc_36", desc => "cand_soft_desc_36" },
cand_soft_desc_37 => { sql => "cands.cand_soft_desc_37", desc => "cand_soft_desc_37" },
cand_soft_desc_38 => { sql => "cands.cand_soft_desc_38", desc => "cand_soft_desc_38" },
cand_soft_desc_39 => { sql => "cands.cand_soft_desc_39", desc => "cand_soft_desc_39" },
cand_soft_desc_4 => { sql => "cands.cand_soft_desc_4", desc => "cand_soft_desc_4" },
cand_soft_desc_40 => { sql => "cands.cand_soft_desc_40", desc => "cand_soft_desc_40" },
cand_soft_desc_5 => { sql => "cands.cand_soft_desc_5", desc => "cand_soft_desc_5" },
cand_soft_desc_6 => { sql => "cands.cand_soft_desc_6", desc => "cand_soft_desc_6" },
cand_soft_desc_7 => { sql => "cands.cand_soft_desc_7", desc => "cand_soft_desc_7" },
cand_soft_desc_8 => { sql => "cands.cand_soft_desc_8", desc => "cand_soft_desc_8" },
cand_soft_desc_9 => { sql => "cands.cand_soft_desc_9", desc => "cand_soft_desc_9" },
cand_soft_expiry_1 => { sql => "cands.cand_soft_expiry_1", desc => "cand_soft_expiry_1" },
cand_soft_expiry_10 => { sql => "cands.cand_soft_expiry_10", desc => "cand_soft_expiry_10" },
cand_soft_expiry_11 => { sql => "cands.cand_soft_expiry_11", desc => "cand_soft_expiry_11" },
cand_soft_expiry_12 => { sql => "cands.cand_soft_expiry_12", desc => "cand_soft_expiry_12" },
cand_soft_expiry_13 => { sql => "cands.cand_soft_expiry_13", desc => "cand_soft_expiry_13" },
cand_soft_expiry_14 => { sql => "cands.cand_soft_expiry_14", desc => "cand_soft_expiry_14" },
cand_soft_expiry_15 => { sql => "cands.cand_soft_expiry_15", desc => "cand_soft_expiry_15" },
cand_soft_expiry_16 => { sql => "cands.cand_soft_expiry_16", desc => "cand_soft_expiry_16" },
cand_soft_expiry_17 => { sql => "cands.cand_soft_expiry_17", desc => "cand_soft_expiry_17" },
cand_soft_expiry_18 => { sql => "cands.cand_soft_expiry_18", desc => "cand_soft_expiry_18" },
cand_soft_expiry_19 => { sql => "cands.cand_soft_expiry_19", desc => "cand_soft_expiry_19" },
cand_soft_expiry_2 => { sql => "cands.cand_soft_expiry_2", desc => "cand_soft_expiry_2" },
cand_soft_expiry_20 => { sql => "cands.cand_soft_expiry_20", desc => "cand_soft_expiry_20" },
cand_soft_expiry_21 => { sql => "cands.cand_soft_expiry_21", desc => "cand_soft_expiry_21" },
cand_soft_expiry_22 => { sql => "cands.cand_soft_expiry_22", desc => "cand_soft_expiry_22" },
cand_soft_expiry_23 => { sql => "cands.cand_soft_expiry_23", desc => "cand_soft_expiry_23" },
cand_soft_expiry_24 => { sql => "cands.cand_soft_expiry_24", desc => "cand_soft_expiry_24" },
cand_soft_expiry_25 => { sql => "cands.cand_soft_expiry_25", desc => "cand_soft_expiry_25" },
cand_soft_expiry_26 => { sql => "cands.cand_soft_expiry_26", desc => "cand_soft_expiry_26" },
cand_soft_expiry_27 => { sql => "cands.cand_soft_expiry_27", desc => "cand_soft_expiry_27" },
cand_soft_expiry_28 => { sql => "cands.cand_soft_expiry_28", desc => "cand_soft_expiry_28" },
cand_soft_expiry_29 => { sql => "cands.cand_soft_expiry_29", desc => "cand_soft_expiry_29" },
cand_soft_expiry_3 => { sql => "cands.cand_soft_expiry_3", desc => "cand_soft_expiry_3" },
cand_soft_expiry_30 => { sql => "cands.cand_soft_expiry_30", desc => "cand_soft_expiry_30" },
cand_soft_expiry_31 => { sql => "cands.cand_soft_expiry_31", desc => "cand_soft_expiry_31" },
cand_soft_expiry_32 => { sql => "cands.cand_soft_expiry_32", desc => "cand_soft_expiry_32" },
cand_soft_expiry_33 => { sql => "cands.cand_soft_expiry_33", desc => "cand_soft_expiry_33" },
cand_soft_expiry_34 => { sql => "cands.cand_soft_expiry_34", desc => "cand_soft_expiry_34" },
cand_soft_expiry_35 => { sql => "cands.cand_soft_expiry_35", desc => "cand_soft_expiry_35" },
cand_soft_expiry_36 => { sql => "cands.cand_soft_expiry_36", desc => "cand_soft_expiry_36" },
cand_soft_expiry_37 => { sql => "cands.cand_soft_expiry_37", desc => "cand_soft_expiry_37" },
cand_soft_expiry_38 => { sql => "cands.cand_soft_expiry_38", desc => "cand_soft_expiry_38" },
cand_soft_expiry_39 => { sql => "cands.cand_soft_expiry_39", desc => "cand_soft_expiry_39" },
cand_soft_expiry_4 => { sql => "cands.cand_soft_expiry_4", desc => "cand_soft_expiry_4" },
cand_soft_expiry_40 => { sql => "cands.cand_soft_expiry_40", desc => "cand_soft_expiry_40" },
cand_soft_expiry_5 => { sql => "cands.cand_soft_expiry_5", desc => "cand_soft_expiry_5" },
cand_soft_expiry_6 => { sql => "cands.cand_soft_expiry_6", desc => "cand_soft_expiry_6" },
cand_soft_expiry_7 => { sql => "cands.cand_soft_expiry_7", desc => "cand_soft_expiry_7" },
cand_soft_expiry_8 => { sql => "cands.cand_soft_expiry_8", desc => "cand_soft_expiry_8" },
cand_soft_expiry_9 => { sql => "cands.cand_soft_expiry_9", desc => "cand_soft_expiry_9" },
cand_soft_start_1 => { sql => "cands.cand_soft_start_1", desc => "cand_soft_start_1" },
cand_soft_start_10 => { sql => "cands.cand_soft_start_10", desc => "cand_soft_start_10" },
cand_soft_start_11 => { sql => "cands.cand_soft_start_11", desc => "cand_soft_start_11" },
cand_soft_start_12 => { sql => "cands.cand_soft_start_12", desc => "cand_soft_start_12" },
cand_soft_start_13 => { sql => "cands.cand_soft_start_13", desc => "cand_soft_start_13" },
cand_soft_start_14 => { sql => "cands.cand_soft_start_14", desc => "cand_soft_start_14" },
cand_soft_start_15 => { sql => "cands.cand_soft_start_15", desc => "cand_soft_start_15" },
cand_soft_start_16 => { sql => "cands.cand_soft_start_16", desc => "cand_soft_start_16" },
cand_soft_start_17 => { sql => "cands.cand_soft_start_17", desc => "cand_soft_start_17" },
cand_soft_start_18 => { sql => "cands.cand_soft_start_18", desc => "cand_soft_start_18" },
cand_soft_start_19 => { sql => "cands.cand_soft_start_19", desc => "cand_soft_start_19" },
cand_soft_start_2 => { sql => "cands.cand_soft_start_2", desc => "cand_soft_start_2" },
cand_soft_start_20 => { sql => "cands.cand_soft_start_20", desc => "cand_soft_start_20" },
cand_soft_start_21 => { sql => "cands.cand_soft_start_21", desc => "cand_soft_start_21" },
cand_soft_start_22 => { sql => "cands.cand_soft_start_22", desc => "cand_soft_start_22" },
cand_soft_start_23 => { sql => "cands.cand_soft_start_23", desc => "cand_soft_start_23" },
cand_soft_start_24 => { sql => "cands.cand_soft_start_24", desc => "cand_soft_start_24" },
cand_soft_start_25 => { sql => "cands.cand_soft_start_25", desc => "cand_soft_start_25" },
cand_soft_start_26 => { sql => "cands.cand_soft_start_26", desc => "cand_soft_start_26" },
cand_soft_start_27 => { sql => "cands.cand_soft_start_27", desc => "cand_soft_start_27" },
cand_soft_start_28 => { sql => "cands.cand_soft_start_28", desc => "cand_soft_start_28" },
cand_soft_start_29 => { sql => "cands.cand_soft_start_29", desc => "cand_soft_start_29" },
cand_soft_start_3 => { sql => "cands.cand_soft_start_3", desc => "cand_soft_start_3" },
cand_soft_start_30 => { sql => "cands.cand_soft_start_30", desc => "cand_soft_start_30" },
cand_soft_start_31 => { sql => "cands.cand_soft_start_31", desc => "cand_soft_start_31" },
cand_soft_start_32 => { sql => "cands.cand_soft_start_32", desc => "cand_soft_start_32" },
cand_soft_start_33 => { sql => "cands.cand_soft_start_33", desc => "cand_soft_start_33" },
cand_soft_start_34 => { sql => "cands.cand_soft_start_34", desc => "cand_soft_start_34" },
cand_soft_start_35 => { sql => "cands.cand_soft_start_35", desc => "cand_soft_start_35" },
cand_soft_start_36 => { sql => "cands.cand_soft_start_36", desc => "cand_soft_start_36" },
cand_soft_start_37 => { sql => "cands.cand_soft_start_37", desc => "cand_soft_start_37" },
cand_soft_start_38 => { sql => "cands.cand_soft_start_38", desc => "cand_soft_start_38" },
cand_soft_start_39 => { sql => "cands.cand_soft_start_39", desc => "cand_soft_start_39" },
cand_soft_start_4 => { sql => "cands.cand_soft_start_4", desc => "cand_soft_start_4" },
cand_soft_start_40 => { sql => "cands.cand_soft_start_40", desc => "cand_soft_start_40" },
cand_soft_start_5 => { sql => "cands.cand_soft_start_5", desc => "cand_soft_start_5" },
cand_soft_start_6 => { sql => "cands.cand_soft_start_6", desc => "cand_soft_start_6" },
cand_soft_start_7 => { sql => "cands.cand_soft_start_7", desc => "cand_soft_start_7" },
cand_soft_start_8 => { sql => "cands.cand_soft_start_8", desc => "cand_soft_start_8" },
cand_soft_start_9 => { sql => "cands.cand_soft_start_9", desc => "cand_soft_start_9" },
cand_source_code => { sql => "cands.cand_source_code", desc => "cand_source_code" },
cand_st_start => { sql => "cands.cand_st_start", desc => "cand_st_start" },
cand_surname => { sql => "cands.cand_surname", desc => "cand_surname" },
cand_time => { sql => "cands.cand_time", desc => "cand_time" },
cand_transfer => { sql => "cands.cand_transfer", desc => "cand_transfer" },
cand_visa_date => { sql => "cands.cand_visa_date", desc => "cand_visa_date" },
cand_want_rate => { sql => "cands.cand_want_rate", desc => "cand_want_rate" },
cand_wantpos => { sql => "cands.cand_wantpos", desc => "cand_wantpos" },
cand_wantsal => { sql => "cands.cand_wantsal", desc => "cand_wantsal" },
cand_we_expiry => { sql => "cands.cand_we_expiry", desc => "cand_we_expiry" },
cand_we_expiryx => { sql => "cands.cand_we_expiryx", desc => "cand_we_expiryx" },
cand_work_eligibility => { sql => "cands.cand_work_eligibility", desc => "cand_work_eligibility" },
cand_work_eligibilityx => { sql => "cands.cand_work_eligibilityx", desc => "cand_work_eligibilityx" },
cand_work_type => { sql => "cands.cand_work_type", desc => "cand_work_type" },
cand_workext => { sql => "cands.cand_workext", desc => "cand_workext" },
cand_workext_5 => { sql => "cands.cand_workext_5", desc => "cand_workext_5" },
cand_worktel => { sql => "cands.cand_worktel", desc => "cand_worktel" },
cand_xmas => { sql => "cands.cand_xmas", desc => "cand_xmas" },
                },
                responses => $default_responses,
            },
        },
        '/candidate/{candNo}' => {
            get => {
                summary => 'Returns candidate details',
                operationId => 'GetCandidateDetails',
                parameters => {
                                candNo       => { sql => 'cands.cand_cand_no', desc => "Candidate Number" },
                },
                responses => $default_responses,
            },
        },
        '/cand_gdpr_refusal/{candNo}' => {
            post => {
                summary => 'Set candidate GDPR refusal',
                operationId => 'CandidateGRPRRefusal',
                parameters => {
                                candNo       => { sql => 'cands.cand_cand_no', desc => "Candidate Number" },
                },
                responses => $default_responses,
            },
        },
        '/cand_gdpr_accept/{candNo}' => {
            post => {
                summary => 'Set candidate GDPR acceptance',
                operationId => 'CandidateGRPRAcceptance',
                parameters => {
                                candNo       => { sql => 'cands.cand_cand_no', desc => "Candidate Number" },
                },
                responses => $default_responses,
            },
        },
    },
    info => {
        version => '0.0.3 (2017-18-31)',
        contact => {
                    name => 'info@talisman-recruitment.com',
                },
        termsOfService => 'http://talisman-recruitment.com/terms/',
        title => 'Beacon Talisman REST API',
        license => {
                    url => 'http://talisman-recruitment.com/terms/',
                    name => 'Proprietary. All rights reserved. Copyright (c) Beacon Computers, Dunstable, UK, 2016.',
                },
        description => 'API for accessing Beacon Talisman recruitment software.\n',
    },
    swagger => '2.0',
    produces => [
            'application/json'
    ],
    consumes => [
            'application/json'
    ],
    basePath => '/api/v1',
    host => 'localhost:5000',
    schemes => [
        'http',
        'https'
    ],
};
